name: conecta_app
description: App de relacionamento com Hive e suporte a imagens locais
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Banco de dados local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Acesso a arquivos locais
  path_provider: ^2.1.2

  # Seleção de imagens da galeria
  image_picker: ^1.0.7

  # Ícones padrão do iOS
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Geração de adapters Hive
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true