name: conecta_app
description: App de relacionamento com verificação de perfil, localização e mapa interativo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Banco de dados local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Localização e distância
  geolocator: ^10.1.0

  # Imagens locais e verificação por selfie
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # Mapa interativo compatível com Windows
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Abrir arquivos (selfie, documentos, etc.)
  file_picker: ^5.5.0

  # Ícones padrão do iOS
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Geração de adapters Hive
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

  # Compatibilidade com Hive Generator
  analyzer: ^6.4.1

flutter:
  uses-material-design: true